# Generated by Django 6.0 on 2025-12-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_filter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberPlateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plates/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='plates/processed/')),
                ('detected_plates', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
